### ISSUE TITLE
Add LF Trademark disclaimer in footer

### ISSUE THREAD

**Issue by jeefy** [AthenZ/website#40]
The CNCF is starting to use a [new tool](https://clomonitor.io/projects/athenz/athenz) to track project requirements and best practices. 

One pretty easy fix to increase AthenZ's score would be to update the footer to include the full LF footer text:

```
Copyright © 2022 The Linux Foundation ®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage page](https://www.linuxfoundation.org/trademark-usage)
```

For some live examples, please see https://prometheus.io/ or https://kubernetes.io 

Feel free to ping me with any questions. Thank you!

**Comment by havetisyan** [comment]
Thanks @jeefy. Updated the website footer to include the LF footer text. I'll take the look at the other issues as listed in the tool to increase the score further.
